# Generated by Django 4.1.5 on 2023-06-21 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FloorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operational', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('moving_up', 'Moving Up'), ('moving_down', 'Moving Down'), ('stopped', 'Stopped')], default='idle', max_length=20)),
                ('current_floor', models.PositiveIntegerField(default=1)),
                ('destination_floor', models.PositiveIntegerField(null=True)),
                ('door', models.CharField(choices=[('open', 'Door is Open'), ('close', 'Door is Closed')], default='closed', max_length=20)),
                ('requests', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.floorrequest')),
            ],
        ),
    ]
