# Generated by Django 4.1.5 on 2023-06-22 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elevator_number', models.IntegerField()),
                ('operational', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('moving_up', 'Moving Up'), ('moving_down', 'Moving Down')], default='idle', max_length=20)),
                ('current_floor', models.PositiveIntegerField(default=0)),
                ('door', models.CharField(choices=[('open', 'Door is Open'), ('close', 'Door is Closed')], default='close', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='ElevatorSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=50)),
                ('total_floors', models.PositiveIntegerField()),
                ('total_elevators', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FloorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_floor', models.PositiveSmallIntegerField()),
                ('destination_floor', models.PositiveSmallIntegerField()),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('elevator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.elevator')),
            ],
        ),
        migrations.AddField(
            model_name='elevator',
            name='elevator_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.elevatorsystem'),
        ),
    ]
