# Generated by Django 4.1.5 on 2023-06-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator',
            name='current_floor',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='elevator',
            name='door',
            field=models.CharField(choices=[('open', 'Door is Open'), ('close', 'Door is Closed')], default='close', max_length=20),
        ),
        migrations.RemoveField(
            model_name='elevator',
            name='requests',
        ),
        migrations.AddField(
            model_name='elevator',
            name='requests',
            field=models.ManyToManyField(blank=True, to='api.floorrequest'),
        ),
    ]
