# Generated by Django 4.1.5 on 2023-06-22 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_elevator_current_floor_alter_elevator_door_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
