# Generated by Django 4.1.5 on 2023-06-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_elevator_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator',
            name='door',
            field=models.CharField(choices=[('open', 'Door is Open'), ('close', 'Door is Closed')], default='close', max_length=5),
        ),
    ]
